services:
  redis-dev:
    container_name: redis-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      - REDIS_PASSWORD=<password>   # 直接設定密碼
      - ALLOW_EMPTY_PASSWORD=no    # 強制要求密碼
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - dev-network

volumes:
  redis_data:

networks:
  dev-network:
    external: true
